version: '3.7'
services:
  aedes:
    container_name: aedes
    image: registry.digitalocean.com/juniper-mqtt/juniper-mqtt:latest
    restart: always
    stop_signal: SIGINT
    networks:
      - mqtt
    ports:
      - '1883:1883'
networks:
  mqtt: